### 数据操作

In [1]:
# 导入torch
import torch

In [2]:
# 张量-一个由数值组成的数组
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 通过张量的shape属性来访问张量（沿每个轴的长度）的形状 
x.shape

torch.Size([12])

In [4]:
# 元素总量
x.numel()

12

In [5]:
# 改变张量形状（reshape不改变元素值）
X = x.reshape(3 ,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# 指定一个维度后可以通过-1来调用此自动计算出维度的功能
X = x.reshape(3, -1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
# 创建全0张量
torch.zeros((3, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# 全1张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

创建一个形状为（3,4）的张量.
其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。

In [11]:
torch.randn(3, 4)

tensor([[ 1.8345, -0.4090, -1.0137,  0.4713],
        [ 1.3246,  1.6441, -0.5726, -0.2133],
        [-0.0859,  0.5470,  0.7259,  1.1965]])

从python列表生成张量

In [12]:
torch.tensor([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [13]:
torch.tensor([[[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]])

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

### 运算符